services:
  - type: web
    name: techfiesta-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false

  - type: worker
    name: techfiesta-celery
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A utils.celery_app.celery worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
