"""Add emotional vectors

Revision ID: 5dcef09a4df7
Revises: 
Create Date: 2026-01-01 14:33:42.641069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcef09a4df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotional_vectors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emotional_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('emotional_history')
        batch_op.drop_column('emotional_vectors')

    # ### end Alembic commands ###
